### ISSUE TITLE
coroutines are required for some of the example

### ISSUE THREAD

**Issue by dietmarkuehl** [facebookexperimental/libunifex#10]
I have tried to build the library with gcc which, unfortunately, doesn't support coroutines, yet. However, the build unconditionally builds the examples and most of them depend on headers including `<experimental/coroutines>`. It would be helpful to have a `cmake` option to avoid building the corresponding examples.

**Comment by lewissbaker** [comment]
With #12 it should now auto-detect whether coroutine support is present and avoid including/defining the parts that depend on coroutines.

You can override this auto-detection rules by adding `-DUNIFEX_HAVE_COROUTINES=0` to the `CMAKE_CXX_FLAGS` variable on the command-line.

**Comment by lewissbaker** [comment]
This has now been merged.
Define `-DUNIFEX_NO_COROUTINES=1` to disable coroutines (it should auto-detect by default but you can override by defining this macro).

**Comment by ericniebler** [comment]
@dietmarkuehl I've beefed up the cmake scripts to do a better job of auto-detecting what features are available, including both coroutines and `<memory_resource>`. Give it a spin.

**Comment by dietmarkuehl** [comment]
The code certainly builds with  gcc. I haven't managed to build a recent LLVM but I'd believe it is working there, too. There were also some other changes you made such that everything is building with gcc!

Thank you very much!
