### ISSUE TITLE
The via() and on() algorithms should take a scheduler

### ISSUE THREAD

**Issue by lewissbaker** [facebookexperimental/libunifex#15]
The via() and on() algorithms currently take a sender that represents the execution context transition rather than taking the scheduler. This means the caller needs to explicitly call `schedule(s)` to get the sender to use.

These algorithms should be changed to take a scheduler instead.

We may need to add two new algorithms that compose senders in the way that these algorithms currently do to replace their utility.

**Comment by lewissbaker** [comment]
PR #44 changes on() to take a scheduler. Still need to tackle via().

**Comment by lewissbaker** [comment]
PR #47 changes `typed_via()` to take a scheduler.

**Comment by janondrusek** [comment]
@lewissbaker is this OK to close? Seems like `via()` was addressed in PR #273.
