### ISSUE TITLE
Users of libunifex?

### ISSUE THREAD

**Issue by msimberg** [facebookexperimental/libunifex#214]
The README quite clearly states that libunifex is experimental and the API and ABI may change at any time. However, I'm wondering if libunifex is already being used in any projects more seriously despite that, either at facebook or elsewhere? To try to make this into something of a feature request, a list of projects (if any) using libunifex would be an interesting complement to the examples in the repo itself, to see how it can be used in real projects. Obviously for this to be useful those projects would have to be public...

A more general follow up question: The long term goal of this is obviously inclusion in the standard. How do you see libunifex's role until that happens? Are you planning to keep it as a prototype or gradually make it into something more production ready/stable?

**Comment by zeyangl** [comment]
I'm aware of one project that uses libunifex, though not sure to what extent it uses it.
https://github.com/star-e/StarEngine

**Comment by ericniebler** [comment]
It is hard to know who is using what open source project. Most of Facebook's mobile apps on the major platforms now use libunifex. I'm also aware of other projects employing the sender/receiver abstraction, if not libunifex itself. One such example is [HPX](https://github.com/STEllAR-GROUP/hpx).

> Are you planning to keep it as a prototype or gradually make it into something more production ready/stable?

It will probably never guarantee ABI stability. As parts of libunifex get standardized, I expect we'll declare those parts API-stable. That's probably all we're likely to guarantee, though.

**Comment by Tradias** [comment]
[asio-grpc](https://github.com/Tradias/asio-grpc) has a libunifex backend that allows writing asynchronous gRPC clients and servers based on the sender/receiver model (in addition to Boost.Asio).

I quick search through the vcpkg ports list shows that it is the only library depending on libunifex though.

**Comment by janondrusek** [comment]
Based on https://github.com/cplusplus/papers/issues/755 and contributions from @ccotter we assume Bloomberg is also using it.
