### ISSUE TITLE
Example to define a receiver?

### ISSUE THREAD

**Issue by ChuanqiXu9** [facebookexperimental/libunifex#224]
I am confused about when and where should I define a receiver. From the example in libunifex, I only find the definition for sender instead of receiver. I want to know in what situation should we define a receiver and how should we implement it.

**Comment by star-e** [comment]
I'm also learning libunifex and I think receiver is the final customization stage of the entire async operation.
For example, If we don't want to use the result from the sender, we might define a dummy_receiver.
```
struct dummy_receiver {
    void set_value() && noexcept {}
    void set_error(std::exception_ptr) && noexcept {}
    void set_done() && noexcept {}
};

void test() {
    single_thread_context ctx;
    std::promise<void> p;
    auto f = p.get_future();
    schedule(ctx.get_scheduler())
        | transform([p = std::move(p)]() mutable {
                p.set_value();
            })
        | submit(dummy_receiver{});
    f.get();
}
```
dummy_receiver does not do any synchronization (unlike sync_wait), and can be used with unifex::submit.
unifex::submit will allocate operation state on heap if the sender run on different context.
We can use get_allocator CPO (customization point object) to customize memory allocation.
```
struct pmr_receiver {
    using allocator_type = std::pmr::polymorphic_allocator<std::byte>;
    allocator_type get_allocator() const noexcept {
        return mAllocator;
    }
    pmr_receiver(allocator_type alloc)
        : mAllocator(alloc)
    {}
    friend allocator_type tag_invoke(unifex::tag_t<unifex::get_allocator>, const pmr_receiver& t) noexcept {
        return t.get_allocator();
    }
    void set_value() && noexcept {}
    void set_error(std::exception_ptr) && noexcept {}
    void set_done() && noexcept {}

    allocator_type mAllocator;
};
```
These are the two receivers I found very useful.

**Comment by ChuanqiXu9** [comment]
> I'm also learning libunifex and I think receiver is the final customization stage of the entire async operation.
> For example, If we don't want to use the result from the sender, we might define a dummy_receiver.
> 
> ```
> struct dummy_receiver {
>     void set_value() && noexcept {}
>     void set_error(std::exception_ptr) && noexcept {}
>     void set_done() && noexcept {}
> };
> 
> void test() {
>     single_thread_context ctx;
>     std::promise<void> p;
>     auto f = p.get_future();
>     schedule(ctx.get_scheduler())
>         | transform([p = std::move(p)]() mutable {
>                 p.set_value();
>             })
>         | submit(dummy_receiver{});
>     f.get();
> }
> ```
> 
> dummy_receiver does not do any synchronization (unlike sync_wait), and can be used with unifex::submit.
> unifex::submit will allocate operation state on heap if the sender run on different context.
> We can use get_allocator CPO (customization point object) to customize memory allocation.
> 
> ```
> struct pmr_receiver {
>     using allocator_type = std::pmr::polymorphic_allocator<std::byte>;
>     allocator_type get_allocator() const noexcept {
>         return mAllocator;
>     }
>     pmr_receiver(allocator_type alloc)
>         : mAllocator(alloc)
>     {}
>     friend allocator_type tag_invoke(unifex::tag_t<unifex::get_allocator>, const pmr_receiver& t) noexcept {
>         return t.get_allocator();
>     }
>     void set_value() && noexcept {}
>     void set_error(std::exception_ptr) && noexcept {}
>     void set_done() && noexcept {}
> 
>     allocator_type mAllocator;
> };
> ```
> 
> These are the two receivers I found very useful.

Thanks for your reply! I agree with you example. And my point is how should we implement receiver if we want to `use the result from the sender`? I think the case where we don't use the result from the receiver seems to be rare.

And according to my experience,  it is more common

**Comment by ChuanqiXu9** [comment]
> I'm also learning libunifex and I think receiver is the final customization stage of the entire async operation.
> For example, If we don't want to use the result from the sender, we might define a dummy_receiver.
> 
> ```
> struct dummy_receiver {
>     void set_value() && noexcept {}
>     void set_error(std::exception_ptr) && noexcept {}
>     void set_done() && noexcept {}
> };
> 
> void test() {
>     single_thread_context ctx;
>     std::promise<void> p;
>     auto f = p.get_future();
>     schedule(ctx.get_scheduler())
>         | transform([p = std::move(p)]() mutable {
>                 p.set_value();
>             })
>         | submit(dummy_receiver{});
>     f.get();
> }
> ```
> 
> dummy_receiver does not do any synchronization (unlike sync_wait), and can be used with unifex::submit.
> unifex::submit will allocate operation state on heap if the sender run on different context.
> We can use get_allocator CPO (customization point object) to customize memory allocation.
> 
> ```
> struct pmr_receiver {
>     using allocator_type = std::pmr::polymorphic_allocator<std::byte>;
>     allocator_type get_allocator() const noexcept {
>         return mAllocator;
>     }
>     pmr_receiver(allocator_type alloc)
>         : mAllocator(alloc)
>     {}
>     friend allocator_type tag_invoke(unifex::tag_t<unifex::get_allocator>, const pmr_receiver& t) noexcept {
>         return t.get_allocator();
>     }
>     void set_value() && noexcept {}
>     void set_error(std::exception_ptr) && noexcept {}
>     void set_done() && noexcept {}
> 
>     allocator_type mAllocator;
> };
> ```
> 
> These are the two receivers I found very useful.

Thanks for your reply! I agree with you example. And my point is how should we implement receiver if we want to `use the result from the sender`? I think the case where we don't use the result from the receiver seems to be rare.

And according to my experience,  it is more common to use the result to create another async operation. (So we need to use then in P0443 and transform in libunifex, right?). So as a user of libunifex, it seems like we only need to write dummy receiver as the end for the chain of async operations?

**Comment by star-e** [comment]
The users of unifex do not write receivers usually. The algorithms will make receivers for us.
For example, unifex::transform(P0443 then) takes a callback and convert it into a receiver, and then the receiver is connected to the precedent sender.
So we can use unifex::transform to inspect the result, instead of writing our own receiver.
I believe we only need receiver at the end of the chain.

**Comment by ChuanqiXu9** [comment]
> The users of unifex do not write receivers usually. The algorithms will make receivers for us.
> For example, unifex::transform(P0443 then) takes a callback and convert it into a receiver, and then the receiver is connected to the precedent sender.
> So we can use unifex::transform to inspect the result, instead of writing our own receiver.
> I believe we only need receiver at the end of the chain.

Is the user of libunifex here mainly refer to who want to implement an executor?

**Comment by star-e** [comment]
The presentations from the authors are really helpful to understand P0443.
[CppCon 2019: Eric Niebler, David Hollman “A Unifying Abstraction for Async in C++”](https://www.youtube.com/watch?v=tF-Nz4aRWAM)
[Structured Concurrency: Writing Safer Concurrent Code with Coroutines... - Lewis Baker - CppCon 2019](https://www.youtube.com/watch?v=1Wy5sq3s2rg)
[C++Now 2017: Kirk Shoop "No raw std::thread! - Live Tweet Analysis in C++"](https://www.youtube.com/watch?v=1-8gxwGN3S8&t=1786s)

**Comment by star-e** [comment]
> 
> 
> > The users of unifex do not write receivers usually. The algorithms will make receivers for us.
> > For example, unifex::transform(P0443 then) takes a callback and convert it into a receiver, and then the receiver is connected to the precedent sender.
> > So we can use unifex::transform to inspect the result, instead of writing our own receiver.
> > I believe we only need receiver at the end of the chain.
> 
> Is the user of libunifex here mainly refer to who want to implement an executor?

No, the users here are not library writers. They just do async programming.

**Comment by ChuanqiXu9** [comment]
> CppCon 2019: Eric Niebler, David Hollman “A Unifying Abstraction for Async in C++”

Thanks for sharing!



> > > The users of unifex do not write receivers usually. The algorithms will make receivers for us.
> > > For example, unifex::transform(P0443 then) takes a callback and convert it into a receiver, and then the receiver is connected to the precedent sender.
> > > So we can use unifex::transform to inspect the result, instead of writing our own receiver.
> > > I believe we only need receiver at the end of the chain.
> > 
> > 
> > Is the user of libunifex here mainly refer to who want to implement an executor?
> 
> No, the users here are not library writers. The users who do async programming.

Oh I got it. I find that the `static_thread_pool` in libunifex seems to be less powerful as other executors like Seastar. And I find that most of the codes consists of basic utilities for executors. So I think libunifex is a library for who want to write an executor based on P0443. However, the library writers are not the intended user, right?

**Comment by LeeHowes** [comment]
> However, the library writers are not the intended user, right?

That depends on what you mean.

libunifex is not a complete production library for concurrency. It's a prototype that is being written - so it isn't complete. In that sense yes, a "user" might want to write an algorithm, an executor, or some execution context based on the rest of libunifex and have it be compatible. That person might write a receiver, in much the same way that many algorithms in libunifex do.

The end user, the user who is writing an application and is using libunifex as a part of the infrastructure of the application should never be writing a receiver. The dummy_receiver that drops the data in particular should more or less never be needed, and submit should never be called by an end user. Instead any sender should be consumed by something that owns its lifetime:
 * co_await, so that a coroutine waits on a sender and the lifetime is owned by that coroutine. The co_await implementation would implement a receiver.
 * sync_wait if you are not in async code any more, maybe your main function needs to wait on some work or libunifex was only used for parallelism inside an otherwise serial application. Sync_wait is not advised from inside an executor of course because mixing blocking and non-blocking work is ill advised.
 * Adding to an async scope. This is the closest to fire and forget - you hand ownership to the scope and can ensure that all the work finishes before some next phase or before the application shuts down.

in all of these cases only if the "user" is the author of "co_await" for some coroutine promise type, or one of the other algorithms, would there be a need to write a receiver. This is much the same as with coroutines, almost nobody needs to write a promise type. Most users just co_await one coroutine from another with a well-defined return type.

**Comment by ChuanqiXu9** [comment]
> > However, the library writers are not the intended user, right?
> 
> That depends on what you mean.
> 
> libunifex is not a complete production library for concurrency. It's a prototype that is being written - so it isn't complete. In that sense yes, a "user" might want to write an algorithm, an executor, or some execution context based on the rest of libunifex and have it be compatible. That person might write a receiver, in much the same way that many algorithms in libunifex do.
> 
> The end user, the user who is writing an application and is using libunifex as a part of the infrastructure of the application should never be writing a receiver. The dummy_receiver that drops the data in particular should more or less never be needed, and submit should never be called by an end user. Instead any sender should be consumed by something that owns its lifetime:
> 
> * co_await, so that a coroutine waits on a sender and the lifetime is owned by that coroutine. The co_await implementation would implement a receiver.
> * sync_wait if you are not in async code any more, maybe your main function needs to wait on some work or libunifex was only used for parallelism inside an otherwise serial application. Sync_wait is not advised from inside an executor of course because mixing blocking and non-blocking work is ill advised.
> * Adding to an async scope. This is the closest to fire and forget - you hand ownership to the scope and can ensure that all the work finishes before some next phase or before the application shuts down.
> 
> in all of these cases only if the "user" is the author of "co_await" for some coroutine promise type, or one of the other algorithms, would there be a need to write a receiver. This is much the same as with coroutines, almost nobody needs to write a promise type. Most users just co_await one coroutine from another with a well-defined return type.

I got it. Thanks for your explanation. And finally, what does `an async scope` mean? I didn't see that in libunifex.

**Comment by LeeHowes** [comment]
@ChuanqiXu9 It looks like we didn't add it to libunifex. Something like the folly one is what I mean: https://github.com/facebook/folly/blob/master/folly/experimental/coro/AsyncScope.h It's an object that acts as a scope, so it takes ownership of awaitables/senders and is itself awaitable to join some set of in-flight tasks. It is much safer than firing and forgetting tasks because it gives you a way to wait on some set of tasks and know that they are no longer referencing data before you delete the data the tasks depend on.

**Comment by ChuanqiXu9** [comment]
> @ChuanqiXu9 It looks like we didn't add it to libunifex. Something like the folly one is what I mean: https://github.com/facebook/folly/blob/master/folly/experimental/coro/AsyncScope.h It's an object that acts as a scope, so it takes ownership of awaitables/senders and is itself awaitable to join some set of in-flight tasks. It is much safer than firing and forgetting tasks because it gives you a way to wait on some set of tasks and know that they are no longer referencing data before you delete the data the tasks depend on.

Thanks for sharing. I think it is benefit to add this utility to libunifex.
