### ISSUE TITLE
cmake scripts lack install command

### ISSUE THREAD

**Issue by ChuanqiXu9** [facebookexperimental/libunifex#231]
It seems like libunifex doesn't support `make install`. Is this an intended behavior? Or do we just forget it?

**Comment by ericniebler** [comment]
It would be nice to have install support. I'm not much of a cmake hacker myself. I would gladly accept a patch.

**Comment by ChuanqiXu9** [comment]
I am not familiar with CMake too. I send a pull request at [233](https://github.com/facebookexperimental/libunifex/pull/233). But due to some reasons, I can't sign at Facebook CLA now. So it seems this pull request can't be merged. 
And that patch is very simple, I am open if any one want to send it again or just drop it.
