### ISSUE TITLE
Issues regarding `transform_done`

### ISSUE THREAD

**Issue by Chlorie** [facebookexperimental/libunifex#258]
My understanding of `transform_done` is that it preserves the input sender's value and error, and produces the result of the given sender-returning function. Thus
```cpp
just_done()
| transform_done([] { return just(42); })
| sync_wait()
```
should produce 42 (wrapped in an `optional<int>`), but currently, it produces 0 for some reasons.

Is my understanding of the `transform_done` algorithm off, or is it an issue in the implementation?

Also a related topic, how could I use `transform_done` together with `transform` so that I can implement something like transforming a sender that sends `T` or done into a sender that sends `optional<T>`?

Thanks.

**Comment by Chlorie** [comment]
Also, I think that there's some discrepancy between the names of the algorithms. `transform` takes a normal synchronous function and transforms the result(s) from the `set_value` signal with that function, while `transform_done` takes a function that produces an inherently asynchronous sender to "transform" the `set_done` signal, which is what apparently the `let` algorithm does. There's not much consistency that which algorithms take synchronous callable and which algorithms take sender-returning ones. Maybe `transform_done` should be renamed as `let_done`? I don't know...

**Comment by ericniebler** [comment]
> Also, I think that there's some discrepancy between the names of the algorithms.

I was just discussing this with the other maintainers a couple of weeks ago. I think we decided on renaming `transform` to `then`, and then making `transform_value`, `transform_error`, and `transform_done` consistent with the arguments they take. That will leave us room to add a `transform` algorithm later that applies a transformation to the elements of a stream.

**Comment by LeeHowes** [comment]
I think the alternative is to make them forms of let. The behaviour of transform_done is really consistent with let rather than with transform. So let->let_value, transform_error->let_error, transform_done->let_done would be consistent.

and transform->then

unless transform has different lifetime semantics from let? Presumably it can't though once it has the ability to deal with an asynchronous return value.
