### ISSUE TITLE
Cannot work with GCC when -fcoroutines is enabled

### ISSUE THREAD

**Issue by npuichigo** [facebookexperimental/libunifex#284]
[This line](https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/get_stop_token.hpp#L46) of deduction failed when using GCC.

**Comment by npuichigo** [comment]
@ericniebler

**Comment by zmcity** [comment]
I meet the same problem in gcc10.2

error: deduction guide 'unifex::_get_stop_token::_fn::_awaitable::_awaiter(StopToken) -> unifex::_get_stop_token::_fn::_awaitable::_awaiter<StopToken>' must be declared at namespace scope

**Comment by ericniebler** [comment]
Any patches are welcome. I'll get to this eventually, but it is not at the top of of my list.

**Comment by williamspatrick** [comment]
@ericniebler Do you know why that deduction guide is there?  It doesn't seem necessary in light of P0091 (Template argument deduction for class templates) which went into C++17.  I've tried compiling on gcc-10 without it and the examples are successful.

**Comment by williamspatrick** [comment]
I also tried clang-12 and it seemed to pass.  I may submit a PR to just remove the deduction guide and see what CI reports as broken.
