### ISSUE TITLE
Does io_uring_context support multiple IO threads?

### ISSUE THREAD

**Issue by npuichigo** [facebookexperimental/libunifex#303]
It seems that only remote queue is atomic, while local queue and pending IO queue are not thread local. How can I use multiple threads for io_uring_context?

**Comment by lewissbaker** [comment]
The io_uring_context supports connect/start of schedule and IO operations from any thread and will automatically reschedule onto the single IO thread if needed before submitting to the SQE buffer.

Completions are always dispatched onto the IO thread.

If you want multiple threads to handle completions then you need to use multiple io_uring_context objects, one for each thread.

**Comment by npuichigo** [comment]
Thanks for your reply. Another question is that will io_uring_context support kernel size polling which has better performance?

**Comment by lewissbaker** [comment]
In theory it could support kernel-side polling - maybe with an optional constructor parameter to switch to this behaviour.

It's not _always_ better performance, though - as it requires having another kernel thread basically spinning polling for new submissions which can take CPU time away from other things the application/machine might want to be doing.

**Comment by npuichigo** [comment]
Thanks
