### ISSUE TITLE
io_uring_context may hang under high IO loads

### ISSUE THREAD

**Issue by npuichigo** [facebookexperimental/libunifex#315]
Recently, I extend io_uring_context to support TCP socket just like what [g6-net](https://github.com/Garcia6l20/g6-net) does. When doing press test, io_uring_context may hang under high IO loads when calling `io_uring_enter`. (my linux kernel is 5.8)
```
io_uring_enter() - submit 0, wait for 1, sqUnflushedCount 0, cqPendingCount 2
```

Here I use io_uring_context together with coroutine like:
```c++
io_context ctx;
inplace_stop_source stop_source;
std::thread t{[&] { ctx.run(stop_source.get_token()); }};

sync_wait([&]() -> task<void> {
    auto listener = listen_on(scheduler, 6666);
    while (true) {
      auto[socket, client_address] = co_await async_accept(listener);
      char data[1024];
      auto bytes_read = co_await async_recv(socket, as_writable_bytes(span{data}));
      co_await async_send(socket, as_bytes(span{message, strlen(message)}));
    }
  }());
```

Before task affinity feature is added, the coroutine is resumed just on the IO thread, hence a `remote_queue_event_user_data` cannot be consumed because no `schedule_remote` is called. This can be showed from the log that we have two cqPendingCount entities lest (one for IORING_OP_ACCEPT and one for IORING_OP_POLL_ADD). I don't know whether this is by design, or is related to the hanging issue. Or maybe there's any potential bug when using io_uring.

**Comment by lewissbaker** [comment]
Having the I/O thread blocked in `io_uring_enter()` while waiting for either an IORING_OP_ACCEPT or an IORING_OP_POLL_ADD event seems like a normal scenario that would occur if the I/O thread becomes idle and there are no more incoming connections.

If you want the application to shut-down you would need to make sure that the `async_accept` operation supports cancellation and that once you are finished connecting to it that you send a stop-request by calling `.request_stop()` on the stop-source. This should then cause the IORING_OP_ACCEPT operation to complete with an operation-aborted result and then exit the coroutine task and cause `sync_wait` to return.

Do you have a more complete example we can run that shows the problem you are observing?

**Comment by npuichigo** [comment]
I wrote some demo codes [here](https://github.com/npuichigo/crpc) and u can use benchmarking tool like [wrk](https://github.com/wg/wrk) to test the server. It's nice of you to take a look.

The server may hang if you increase the connections and extend the testing duration.

**Comment by npuichigo** [comment]
I find that the issue my own fault that I don't correctly use coroutine here. After accepting a request, I don't spwan to handle the request but co_await the `read` and `write`, which makes `accept` starves to death. After comparing with asio's example, I can fix the hang issue by using async_scope.spwan like this:
```c++
io_context ctx;
inplace_stop_source stop_source;
std::thread t{[&] { ctx.run(stop_source.get_token()); }};

task<void> echo(io_context::async_socket socket) {
  char data[1024];
  auto bytes_read = co_await async_recv(socket, as_writable_bytes(span{data}));
  co_await async_send(socket, as_bytes(span{data, bytes_read}));
}

sync_wait([&]() -> task<void> {
    auto listener = listen_on(scheduler, 6666);
    async_scope scope;
    while (true) {
      auto[socket, client_address] = co_await async_accept(listener);
      scope.spawn(echo(std::move(socket)));
    }
  }());
```
Sorry for misreporting the bug.
