### ISSUE TITLE
Add a utility for adding the ability to stop an unstoppable sender with a layer of indirection

### ISSUE THREAD

**Issue by ericniebler** [facebookexperimental/libunifex#317]

**Comment by lewissbaker** [comment]
Is the idea here to allow wrapping a sender with something that uses an async-scope and then having it detach-on-cancellation and immediately complete with set_done but still have the async-scope join the completion of that operation?

**Comment by ispeters** [comment]
Is this `detach_on_cancel`?

**Comment by ispeters** [comment]
I take Lewis' thumbs-up to mean this is resolved with `detach_on_cancel`.
