### ISSUE TITLE
simple usage of transform & sync_wait with compile error

### ISSUE THREAD

**Issue by zeyangl** [facebookexperimental/libunifex#368]
I tried writing a shortest unifex example possible and came up with this

![image](https://user-images.githubusercontent.com/1244606/139811478-ddc8818c-402e-4648-a647-592c03f0fd97.png)

I'm curious as why sync_wait is not compiling. The error is a bit too obfiscated for someone not very familiar with unifex yet. If I return void from the second function it works fine. After inspecting transform's definition it seems to allow returning custom values.

I'm using vcpkg's version of unifex(when "then" is still "transform"), and in visual studio 2019.

Thanks.

**Comment by RishabhRD** [comment]
I am not an expert but, I don't know if ``[](){}`` is even a sender. You can try:
```cpp
  auto cc = then(just(), [] { return 0; });
  auto x = sync_wait(cc);
  EXPECT_EQ(x.value(), 0);
```

You can use ``transform`` if you are using that version. As of my limited knowledge, ``just()`` is a sender that just completes by calling ``set_value()`` with no arguments (If ``just`` with called with arguments it would call ``set_value`` with those arguments). So, it should serve your purpose.

**Comment by zeyangl** [comment]
Thanks. I thought the lambda could be implicitly packaged as a sender. I went through the unit tests and found them to be very helpful learning the patterns.

**Comment by kirkshoop** [comment]
@RishabhRD is correct. 
Thanks for the question and the answer!

**Comment by zeyangl** [comment]
It might be helpful to point readers to the unit tests in the docs, better than examples for initial learning.
