### ISSUE TITLE
Adopt a unit-testing framework

### ISSUE THREAD

**Issue by lewissbaker** [facebookexperimental/libunifex#39]
The tests we have at the moment are mostly smoke-tests/examples that check that things compile and at least pass some basic runtime checks.

If we want to write more comprehensive tests then we should consider making use of a unit-test framework (eg. googletest, catch2, etc.) for writing the tests.

**Comment by ericniebler** [comment]
I vote against catch2. I have bad experiences with catch2 greatly increasing compile times. (Ironic for me to be complaining about that, no?)

**Comment by ericniebler** [comment]
I'm remembering that I did work to make pushmi use GTest and wrote some cmake to make it happen: https://github.com/facebookresearch/pushmi/blob/master/cmake/CMakeLists.txt.in

We should steal that.
