### ISSUE TITLE
Why this code does not compile

### ISSUE THREAD

**Issue by abhilashraju** [facebookexperimental/libunifex#427]
I am curious to know why this code doesn't compile?
```
int main() {
   single_thread_context ctx;
 
//    auto first = just(20)|then([](auto v){return v;});
    auto first = ctx.get_scheduler()|then([](auto v){return 20;});

     printf("%d",sync_wait(
            then( 
                first,
                [](auto v){return v;})).value());
    return 0;
}
```
https://godbolt.org/z/365c1rxjc
It works fine with just. But I wanted to schedule the work in a separate thread.

**Comment by lewissbaker** [comment]
You need to call `schedule(ctx.get_scheduler())` here to get a sender instead of a scheduler.

**Comment by abhilashraju** [comment]
Thanks I missed that:-)
