### ISSUE TITLE
repeat_effect_until  

### ISSUE THREAD

**Issue by Meigumikato** [facebookexperimental/libunifex#436]
I use repeat_effect_until and execute algorithm to execute an infinitely repeating Sender task, but the program crashes shortly after startup, I checked the core file with GDB and found that there are millions of frames about repeat_effect_until, however when I use execute to add an infinite number of frames There is nothing wrong with the loop, I don't have any ideas to solve this problem, hope to provide some suggestions

```
void Controller::Start() {
  auto schedule_sender =  unifex::just_from([this]{ Schedule();});
  auto repeat_sender = unifex::repeat_effect_until(schedule_sender, [this] { return stopped_; });
  unifex::execute(main_loop_.get_scheduler(), [repeat_sender] {
    unifex::sync_wait(repeat_sender);  // use repeat_sender way
    // while (!stopped_) Schedule();  // use infinitely loop way
  });
}
```

**Comment by janondrusek** [comment]
It looks like you are starting the `repeat_sender` in a loop. A simplified, count down, example of `repeat_effect_until` on [godbolt](https://godbolt.org/z/dbxfv3Y4z). Note the sender is only started once by using `sync_wait`.

A more complete example can be found in [windows_iocp_context_test](https://github.com/facebookexperimental/libunifex/blob/main/test/windows_iocp_context_test.cpp#L149).

**Comment by Meigumikato** [comment]
I want to start asynchronously so I use the execute algorithm, but I don't have a loop to call

**Comment by Meigumikato** [comment]
I Just call Schedule() function, this function not has loop

**Comment by janondrusek** [comment]
Please send a complete example of your code, preferably a *godbolt* link like I posted above. Otherwise I won't be able to help.

**Comment by Meigumikato** [comment]
Thank you very much, I found the problem
