### ISSUE TITLE
Libunifex does not compile on Linux

### ISSUE THREAD

**Issue by dascandy** [facebookexperimental/libunifex#45]
It appears that there is a namespace called `linux`. For some reason, Clang 9 #define's linux to be 1 on my platform (Ubuntu 18.04). I'm using the clang-9 from apt.llvm.org. Error below:

/usr/bin/clang++-9   -I../source/../include -Iinclude -stdlib=libc++ -std=gnu++2a -MD -MT source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o -MF source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o.d -o source/CMakeFiles/unifex.dir/linux/monotonic_clock.cpp.o -c ../source/linux/monotonic_clock.cpp
In file included from ../source/linux/monotonic_clock.cpp:16:
../source/../include/unifex/linux/monotonic_clock.hpp:24:11: error: expected identifier or '{'
namespace linux {
          ^
<built-in>:392:15: note: expanded from here
#define linux 1
              ^

**Comment by dascandy** [comment]
Seems to be caused by running the compiler in `-std=gnu++2a` mode. As this is part of a header, it seems like something to fix because users of this code might run in that mode.

**Comment by kirkshoop** [comment]
Thank you for the report Peter!
