### ISSUE TITLE
How to format code-style 

### ISSUE THREAD

**Issue by Runner-2019** [facebookexperimental/libunifex#479]
Hi, I have an question about how to beautify code style when using pipeline operator. I want the effect as below, 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/59395781/212243106-dd762e35-bcb2-4bc9-9cae-8794433e8e50.png">
But when I using clang-format (Google style), I got this:
<img width="394" alt="image" src="https://user-images.githubusercontent.com/59395781/212243175-a340f077-3b01-46b6-813b-1b204ce98eba.png">
Thanks.

**Comment by Runner-2019** [comment]
added: 
I used clang-format and  I found this solution :
<img width="222" alt="image" src="https://user-images.githubusercontent.com/59395781/212358167-4a463f6f-556d-4c74-a0da-45f007bb4d5b.png">

I wonder if there is a better solution. Anyone who can help me I will call you daddy:)

**Comment by ispeters** [comment]
I haven't found a good solution. The best hack I've found is to put empty `//` comments where you want line breaks. I don't think it'll give you exactly what you're asking for, but maybe it's the least bad option.

**Comment by Runner-2019** [comment]
> I haven't found a good solution. The best hack I've found is to put empty `//` comments where you want line breaks. I don't think it'll give you exactly what you're asking for, but maybe it's the least bad option.

Thanks. I have tried it but I wonder if there have some more elegant ways :)

**Comment by Runner-2019** [comment]
Happy new year！

**Comment by janondrusek** [comment]
The only other option I see is to figure out how to tweak `.clang-format` file, so that the trailing `//` are not necessary. If it does not support such config, you'd need to contribute that to the [clang-format](https://github.com/llvm/llvm-project/tree/main/clang/tools/clang-format) tool.
