### ISSUE TITLE
There is different storage class about unifex::schedule.

### ISSUE THREAD

**Issue by B1aNB1aN** [facebookexperimental/libunifex#513]
At `unifex_fwd.hpp:72`, unifex::schedule is declared as `extern const _schedule::_fn schedule;`. But at `scheduler_concepts.hpp:192`, unifex::schedule is defined as `inline constexpr _schedule::_fn schedule {};`
This will lead to a redefinition compile error.

Dev env: VS 2022 17.5.5
Compiler: cl.exe
Compiler Version: 14.35.32215

**Comment by ericniebler** [comment]
It's because visual c++ is non conforming. See https://learn.microsoft.com/en-us/cpp/build/reference/zc-externconstexpr?view=msvc-170
