### ISSUE TITLE
`submit_cpo` starts the operation twice

### ISSUE THREAD

**Issue by efimovamarina** [facebookexperimental/libunifex#52]
It looks like 'break' operator is missed in `submit_cpo` which leads to double invoking of the operation in some cases.

[https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/submit.hpp#L124](https://github.com/facebookexperimental/libunifex/blob/master/include/unifex/submit.hpp#L124)

**Comment by ericniebler** [comment]
This looks like a legit but to me. @lewissbaker ?
