### ISSUE TITLE
Build failing on commit 98339251024dac5f82a62411ea902127864b8aba

### ISSUE THREAD

**Issue by tinkerbeast** [facebookexperimental/libunifex#56]
The build on the main branch just fails in so many ways. I was wondering if there's a relatively stable commit or branch I can check out to get the build through.

Or maybe get a reference environment (compiler version, OS etc).

Attached build error log for reference.
[build.log.gz](https://github.com/facebookexperimental/libunifex/files/4069441/build.log.gz)

**Comment by ericniebler** [comment]
Thanks for the report. I'm working to get CI running for this project, which should keep trunk healthy. Your best bet is probably clang-9.

**Comment by ericniebler** [comment]
The issues with missing headers was fixed two days ago. I just fixed the problem with accessing private members. Please reopen if you are still seeing problems after sync'ing.
