### ISSUE TITLE
Add initial implementation of "many sender" concept

### ISSUE THREAD

**Issue by lewissbaker** [facebookexperimental/libunifex#67]
Add a "many sender" concept that can send a sequence of calls to a "many receiver":
* zero or more `set_next()` calls followed by;
* a call to one of `set_value()`, `set_done()` or `set_error()`.

Add a `bulk_schedule(scheduler, count)` algorithm that sends `count` calls to `set_next(r, idx)`.
This should have a default implementation in terms of `schedule(scheduler)` 

Add a `get_execution_policy(receiver)` CPO that allows a many-sender to query whether the receiver is able to support unsequenced/concurrent invocations of `set_next()`.

Add some basic many-sender algorithms.
- `reduce()`
- `for_each()`
- `transform()`
- `to_vector()`

**Comment by janondrusek** [comment]
#134 introduced

* [bulk_join](https://github.com/facebookexperimental/libunifex/blob/98bd4548398bcc2505e7d18effc95658a7e07a02/include/unifex/bulk_join.hpp)
* [bulk_schedule](https://github.com/facebookexperimental/libunifex/blob/98bd4548398bcc2505e7d18effc95658a7e07a02/include/unifex/bulk_schedule.hpp)
* [bulk_transform](https://github.com/facebookexperimental/libunifex/blob/98bd4548398bcc2505e7d18effc95658a7e07a02/include/unifex/bulk_transform.hpp)
