### ISSUE TITLE
-stdlib=libc++ should not be forced on when on Linux

### ISSUE THREAD

**Issue by ned14** [facebookexperimental/libunifex#86]
Right now you force it on always if clang is installed, and libc++ is installed. This is anti-social. The vast majority of end users use clang with libstdc++ on Linux, not libc++. They would be surprised if linking in libunifex when using clang on Linux by link errors. If end users specifically want libc++ on Linux, they'll explicitly ask for `-stdlib=libc++` when configuring cmake.

Please change the default on Linux.

**Comment by ericniebler** [comment]
Does libstdc++ support coroutines yet?

**Comment by ned14** [comment]
libstdc++ supports coroutines so well that it causes clang 10 to ICE :)

But that's besides the point. Good etiquette means you probe the compiler toolchain the end user has supplied for working coroutines (flipping on all the various ways one can enable coroutines for the various compilers), and if you can find a compiler which appears to work, only then do you choose those options as part of cmake configuration.

You're about to say "we already do this". But silently swapping out the STL is a BIG surprise for the end user. It produces lots of confusing, unhelpful, link errors. It also only *silently* occurs if the end user just happens to have also installed libc++ on Linux. That's very surprising.

What I would suggest is that if on Linux, and coroutines don't work, print a cmake informational message suggesting that the end user can (a) install a very recent libc++ (probably v10) and (b) install a very recent clang and (c) configure cmake with XXX flags to have libunifex use clang and the libc++ STL instead.

An alternative, though be aware that you will receive flak for this from the build purists, is to programmatically generate target variants permuted by STL variant, shared vs static vs header library, and sanitiser flags. I do this for all my libraries, I find it great because I have lots of CPUs, and impeccable build hygiene, so I can build all those config variants in almost no time. But the price is a constant flow of email and github issues raised by people complaining that they dislike the "misuse of build target graphs" etc etc and won't I "please use conventional cmake build target graph design" etc etc. Please do note that cmake's `add_subdirectory()` has an `EXCLUDE_FROM_ALL` option, which turns the dependency inclusion into a lazily built dependency, so consumers of your library aren't building all the configuration permutations needlessly. Anyway, I digress ...

FYI https://gcc.gnu.org/projects/cxx-status.html suggests that GCC 11 will have Coroutines, so I would assume libstdc++ 11 will also have support.

**Comment by ned14** [comment]
Thanks @kirkshoop for fixing this.
