### ISSUE TITLE
Adopt a concepts-emulation facility to replace raw enable_if-based constraints

### ISSUE THREAD

**Issue by lewissbaker** [facebookexperimental/libunifex#92]
We ideally want to be able to switch to using C++20 concepts if it is available in the current compiler but fall back to traditional SFINAE techniques if not. The hope is that this will give better compile-times and better error-messages when C++20 concepts are available.

We may be able to port and use the concepts emulation bits from the range-v3 library for this purpose.

**Comment by ericniebler** [comment]
Done.
